# Generated by Django 3.1.2 on 2021-10-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211026_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.URLField(max_length=100000),
        ),
    ]
